# Generated by Django 3.2.6 on 2021-08-19 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='field',
            field=models.CharField(default='none defined', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='Not Finished', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 12, 58, 45, 630600)),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
