# Generated by Django 3.2.6 on 2021-08-19 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_auto_20210819_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_name',
            field=models.CharField(default='undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 16, 58, 20, 518685)),
        ),
    ]
