# Generated by Django 3.2.6 on 2021-08-19 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0004_auto_20210819_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('document_name', models.CharField(default='undefined', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 17, 26, 43, 455770)),
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ManyToManyField(to='filemanager.UserDoc'),
        ),
    ]
