# Generated by Django 3.2.6 on 2021-08-19 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0005_auto_20210819_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 17, 28, 28, 798712)),
        ),
    ]
