# Generated by Django 3.2.6 on 2021-08-20 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0006_alter_document_change_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 20, 59, 40, 755375)),
        ),
        migrations.DeleteModel(
            name='UserDoc',
        ),
    ]
